delete from public.world_cup_predictions;

insert into public.world_cup_predictions (
  id,
  match_time,
  stage,
  venue,
  home_name,
  home_code,
  away_name,
  away_code,
  home_win,
  draw,
  away_win,
  predicted_score,
  consensus_pick,
  confidence,
  ai_summary,
  model_breakdown,
  status,
  source_name,
  source_url,
  source_updated_at
) values
  (
    'mex-ecu-2026-07-01',
    '2026-07-01T16:00:00Z',
    'Round of 32',
    'TBD',
    'Mexico',
    'MEX',
    'Ecuador',
    'ECU',
    48.00,
    27.00,
    25.00,
    '1-0',
    'MEX',
    75,
    'ScoreGPT lists Mexico vs Ecuador as a Round of 32 match with an AI pick of 1-0 and 3 of 4 models agreeing.',
    '[{"model":"ScoreGPT consensus","pick":"MEX","score":"1-0","confidence":75},{"model":"Model agreement","pick":"MEX","score":"1-0","confidence":75}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  ),
  (
    'eng-cod-2026-07-01',
    '2026-07-01T19:00:00Z',
    'Round of 32',
    'TBD',
    'England',
    'ENG',
    'D.R. Congo',
    'COD',
    68.00,
    19.00,
    13.00,
    '2-0',
    'ENG',
    100,
    'ScoreGPT lists England vs D.R. Congo with an AI pick of 2-0 and 5 of 5 models agreeing.',
    '[{"model":"ScoreGPT consensus","pick":"ENG","score":"2-0","confidence":100},{"model":"Model agreement","pick":"ENG","score":"2-0","confidence":100}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  ),
  (
    'bel-sen-2026-07-01',
    '2026-07-01T22:00:00Z',
    'Round of 32',
    'TBD',
    'Belgium',
    'BEL',
    'Senegal',
    'SEN',
    55.00,
    24.00,
    21.00,
    '2-1',
    'BEL',
    80,
    'ScoreGPT lists Belgium vs Senegal with an AI pick of 2-1 and 4 of 5 models agreeing.',
    '[{"model":"ScoreGPT consensus","pick":"BEL","score":"2-1","confidence":80},{"model":"Model agreement","pick":"BEL","score":"2-1","confidence":80}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  ),
  (
    'usa-bih-2026-07-02',
    '2026-07-02T16:00:00Z',
    'Round of 32',
    'TBD',
    'USA',
    'USA',
    'Bosnia & Herzegovina',
    'BIH',
    33.34,
    33.33,
    33.33,
    'TBD',
    'TBD',
    0,
    'ScoreGPT lists USA vs Bosnia & Herzegovina as upcoming. Predictions land at 07:30 UTC.',
    '[{"model":"ScoreGPT","pick":"TBD","score":"TBD","confidence":0}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  ),
  (
    'esp-aut-2026-07-02',
    '2026-07-02T19:00:00Z',
    'Round of 32',
    'TBD',
    'Spain',
    'ESP',
    'Austria',
    'AUT',
    33.34,
    33.33,
    33.33,
    'TBD',
    'TBD',
    0,
    'ScoreGPT lists Spain vs Austria as upcoming. Predictions land at 07:30 UTC.',
    '[{"model":"ScoreGPT","pick":"TBD","score":"TBD","confidence":0}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  ),
  (
    'por-cro-2026-07-02',
    '2026-07-02T22:00:00Z',
    'Round of 32',
    'TBD',
    'Portugal',
    'POR',
    'Croatia',
    'CRO',
    33.34,
    33.33,
    33.33,
    'TBD',
    'TBD',
    0,
    'ScoreGPT lists Portugal vs Croatia as upcoming. Predictions land at 07:30 UTC.',
    '[{"model":"ScoreGPT","pick":"TBD","score":"TBD","confidence":0}]',
    'upcoming',
    'ScoreGPT',
    'https://scoregpt.app/world-cup-2026',
    '2026-07-01T07:30:00Z'
  )
on conflict (id) do update set
  match_time = excluded.match_time,
  stage = excluded.stage,
  venue = excluded.venue,
  home_name = excluded.home_name,
  home_code = excluded.home_code,
  away_name = excluded.away_name,
  away_code = excluded.away_code,
  home_win = excluded.home_win,
  draw = excluded.draw,
  away_win = excluded.away_win,
  predicted_score = excluded.predicted_score,
  consensus_pick = excluded.consensus_pick,
  confidence = excluded.confidence,
  ai_summary = excluded.ai_summary,
  model_breakdown = excluded.model_breakdown,
  status = excluded.status,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_updated_at = excluded.source_updated_at,
  updated_at = now();
